'use strict'
module.exports = {
  paths: require('./paths.cjs'),
  ...require('./data-init.cjs'),
  ...require('./validators.cjs'),
  ...require('./config-validator.cjs'),
  ...require('./agent-service.cjs'),
  ...require('./task-bridge.cjs'),
  ...require('./autopilot-state.cjs'),
  departmentService: require('./department-service.cjs'),
  projectService: require('./project-service.cjs'),
  fileBrowser: require('./file-browser.cjs'),
  ...require('./skill-utils.cjs'),
  envManager: require('./env-manager.cjs'),
  modelsService: require('./models-service.cjs'),
  baseRulesInjector: require('./base-rules-injector.cjs'),
  projectStandards: require('./project-standards.cjs'),
  taskStandards: require('./task-standards.cjs'),
  phaseDeliverables: require('./phase-deliverables.cjs'),
  skillSymlinks: require('./skill-symlinks.cjs'),
  eventRelay: require('./event-relay.cjs'),
}
